// Copyright (C) 2026 PDG Global Limited
// SPDX-License-Identifier: AGPL-3.0-or-later

use futures::StreamExt;
use rusty_core::{Message, Role, RustyError};
use rusty_provider::{LlmProvider, MessageRequest, StreamEvent};
use std::path::Path;
use tracing::{debug, info};

// ── Tier thresholds (fraction of context window) ────────────────────────────

/// Tier 1: micro-compaction — replace old tool results with placeholders.
const TIER1_FRACTION: f64 = 0.25;

/// Tier 2: structured extraction — LLM writes checkpoint.md.
const TIER2_FRACTION: f64 = 0.50;

/// Tier 3: full compaction — LLM summarises old messages.
const TIER3_FRACTION: f64 = 0.75;

/// Keep the last N messages un-compacted.
const KEEP_RECENT: usize = 10;

/// Fallback message count threshold for full compaction.
const COMPACT_MESSAGE_THRESHOLD: usize = 40;

/// Tool results longer than this are replaced with a placeholder during micro-compaction.
const MICRO_COMPACT_THRESHOLD_CHARS: usize = 500;

// ── Checkpoint tier tracking ────────────────────────────────────────────────

/// Tracks which checkpoint tiers have fired in the current context growth cycle.
/// After tier 3 (full compaction) shrinks the context, the tier resets.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CheckpointTier {
    None = 0,
    Micro = 1,
    Extracted = 2,
    Compacted = 3,
}

impl CheckpointTier {
    pub fn as_u8(self) -> u8 {
        self as u8
    }

    pub fn from_u8(v: u8) -> Self {
        match v {
            0 => Self::None,
            1 => Self::Micro,
            2 => Self::Extracted,
            _ => Self::Compacted,
        }
    }
}

// ── Tier 1: Micro-compaction ────────────────────────────────────────────────

/// Lightweight compaction: replace old tool results with placeholders.
/// Returns true if any replacements were made.
pub fn micro_compact(messages: &mut Vec<Message>) -> bool {
    let split_point = messages.len().saturating_sub(KEEP_RECENT);
    let mut modified = false;

    for msg in messages.iter_mut().take(split_point) {
        if let rusty_core::MessageContent::Blocks(ref mut blocks) = msg.content {
            for block in blocks.iter_mut() {
                if let rusty_core::ContentBlock::ToolResult { content, .. } = block {
                    if content.len() > MICRO_COMPACT_THRESHOLD_CHARS {
                        let lines = content.lines().count();
                        *content = format!(
                            "[Old tool result content cleared ({lines} lines)]"
                        );
                        modified = true;
                    }
                }
            }
        }
    }

    if modified {
        debug!("Micro-compacted tool results in {} oldest messages", split_point);
    }
    modified
}

// ── Tier 2: Structured extraction ───────────────────────────────────────────

/// Checkpoint template with 11 sections (inspired by MiMo Code).
/// Used to initialize checkpoint.md files and as the target structure for extraction.
pub const CHECKPOINT_TEMPLATE: &str = "\
# Session checkpoint
_Generated by checkpoint writer; structure preserved across updates._

## §1 Active intent
_User's most recent explicit request, verbatim block-quoted from the conversation._

(none yet)

## §2 Next concrete action
_The single next concrete step, derived from §1 and current state._

(none yet)

## §3 Directives (this session)
_Session-specific working style only. Project-level rules are in MEMORY.md._

(none)

## §4 Task tree
_Hierarchical view of tasks with current status._

(none yet)

## §5 Current work
_What was being done immediately before this checkpoint. Mention specific file paths._

(none yet)

## §6 Files and code sections
_Files actively being read or modified. List with one-line purpose._

(none yet)

## §7 Discovered knowledge (cross-task)
_Facts learned during this session that may apply to future tasks._

(none yet)

## §8 Errors and fixes
_Errors encountered this session and how they were resolved._

(none)

## §9 Live resources
_Runtime state: branch, uncommitted files, running processes._

(none yet)

## §10 Design decisions and discussion outcomes
_Decisions reached through discussion. Captures user intent and trade-off rationale._

(none yet)

## §11 Open notes
_Catch-all for items that don't fit other sections. Quotes, unresolved questions._

(none yet)
";

/// Section budgets for checkpoint.md (token estimates per section).
pub const CHECKPOINT_SECTION_BUDGETS: &[(&str, usize)] = &[
    ("§1 Active intent", 500),
    ("§2 Next concrete action", 1000),
    ("§3 Directives (this session)", 800),
    ("§4 Task tree", 1000),
    ("§5 Current work", 2000),
    ("§6 Files and code sections", 1500),
    ("§7 Discovered knowledge (cross-task)", 2000),
    ("§8 Errors and fixes", 1500),
    ("§9 Live resources", 1000),
    ("§10 Design decisions and discussion outcomes", 3000),
    ("§11 Open notes", 800),
];

/// Notes template for the session scratchpad.
pub const NOTES_TEMPLATE: &str = "\
# Session notes
_Free-form scratchpad for the main agent. Append entries as you go; \
the checkpoint writer reconciles them at checkpoint events. \
Format each entry as `## [turn N · timestamp]` followed by free-form body._
";

const CHECKPOINT_PROMPT: &str = "\
You are extracting structured state from a conversation for future reference. \
Read the conversation below and produce a checkpoint with exactly these 11 sections:

## §1 Active intent
The user's most recent explicit request, VERBATIM BLOCK-QUOTED from the conversation.
Format: `> \"exact user words\"`
This is the anchor. Without verbatim, the next-cycle agent will lose the user's actual words.

## §2 Next concrete action
The single next concrete step, derived from §1 and current state.
Include a verbatim quote when the user explicitly stated a next step.

## §3 Directives (this session)
Session-specific working style only (e.g. 'prefer functional methods', 'no try/catch').
Project-level rules belong in MEMORY.md, not here.

## §4 Task tree
Hierarchical view of tasks with status: 🔵 open / 🔄 in_progress / 🟡 blocked / ✅ done / ❌ abandoned.
Source of truth = the todowrite tool's last output.

## §5 Current work
What was being done immediately before this checkpoint. Mention specific file paths and code locations.

## §6 Files and code sections
Files actively being read or modified. List with one-line purpose each.

## §7 Discovered knowledge (cross-task)
Facts learned during this session that may apply to future tasks.
Items here are candidates for promotion to MEMORY.md if they prove durable.

## §8 Errors and fixes
Errors encountered this session and how they were resolved. Newest first.

## §9 Live resources
Runtime state: git branch, uncommitted files, running processes, temp artifacts.

## §10 Design decisions and discussion outcomes
Decisions reached through discussion that produced no immediate code/file artifact.
Captures user intent and trade-off rationale.

## §11 Open notes
Catch-all for items that don't fit §1-§10. Quotes, unresolved questions, micro-observations.

Rules:
- Be concise. Each section should be 1-5 lines.
- Focus on facts, not narration.
- Include file paths and specific technical details.
- §1 MUST contain at least one block-quoted verbatim user request.
- §2 MUST be present and actionable — the agent wakes up with only this checkpoint.
- If a section has nothing, write '(none)' — do not omit sections.";

/// Extract structured checkpoint from conversation history using an LLM call.
/// Writes the result to `checkpoint_path`. If `notes_content` is provided,
/// it is included in the extraction prompt and should be cleared afterward.
pub async fn extract_checkpoint(
    messages: &[Message],
    provider: &dyn LlmProvider,
    system_prompt: &str,
    checkpoint_path: &Path,
    notes_content: Option<&str>,
) -> Result<(), RustyError> {
    let old_text = messages_to_text(messages);

    // Read existing checkpoint if it exists, so we can do incremental updates
    let existing = read_file_content(checkpoint_path).await;

    let mut prompt = String::from(CHECKPOINT_PROMPT);

    if let Some(ref existing_cp) = existing {
        if !existing_cp.trim().is_empty() {
            prompt.push_str("\n\nExisting checkpoint (update incrementally, preserve unchanged sections):\n");
            prompt.push_str(existing_cp);
        }
    }

    if let Some(notes) = notes_content {
        if !notes.trim().is_empty() {
            prompt.push_str("\n\nScratchpad notes from the session (reconcile into appropriate sections, then clear):\n");
            prompt.push_str(notes);
        }
    }

    prompt.push_str("\n\nConversation:\n");
    prompt.push_str(&old_text);

    prompt.push_str("\n\nProduce the full checkpoint with all 11 sections. \
        Use the exact `## §N Title` headers. Update sections incrementally — \
        preserve content that's still accurate, update what changed.");

    let request = MessageRequest {
        model: provider.model().to_string(),
        system: Some(system_prompt.to_string()),
        messages: vec![Message::user(&prompt)],
        tools: vec![],
        max_tokens: 2048,
        temperature: None,
        thinking_budget: None,
    };

    let mut stream = provider.create_message_stream(request).await?;
    let mut checkpoint = String::new();

    while let Some(event) = stream.next().await {
        match event? {
            StreamEvent::TextDelta(text) => checkpoint.push_str(&text),
            StreamEvent::Done { .. } => break,
            StreamEvent::Error(msg) => return Err(RustyError::Api(msg)),
            _ => {}
        }
    }

    // Ensure parent directory exists
    if let Some(parent) = checkpoint_path.parent() {
        tokio::fs::create_dir_all(parent).await.ok();
    }

    tokio::fs::write(checkpoint_path, &checkpoint).await.map_err(|e| {
        RustyError::Other(format!("Failed to write checkpoint: {e}"))
    })?;

    info!("Extracted checkpoint ({} chars)", checkpoint.len());
    Ok(())
}

// ── Tier 3: Full compaction ─────────────────────────────────────────────────

/// Compute the token threshold for a given tier fraction.
fn tier_threshold(context_window: u32, fraction: f64) -> usize {
    (context_window as f64 * fraction) as usize
}

/// Check if compaction is needed and perform it.
/// Handles the three-tier checkpoint system:
/// - Tier 1 (25%): micro-compaction (cheap placeholder replacement)
/// - Tier 2 (50%): structured extraction to checkpoint.md
/// - Tier 3 (75%): full LLM-based compaction
///
/// Returns the highest tier that was executed.
pub async fn maybe_compact(
    messages: &mut Vec<Message>,
    provider: &dyn LlmProvider,
    system_prompt: &str,
    context_window: u32,
    plan_text: Option<&str>,
    last_tier: CheckpointTier,
    notes_path: Option<&Path>,
    checkpoint_path: Option<&Path>,
) -> Result<CheckpointTier, RustyError> {
    let estimated_tokens = estimate_tokens(messages);
    let t1_threshold = tier_threshold(context_window, TIER1_FRACTION);
    let t2_threshold = tier_threshold(context_window, TIER2_FRACTION);
    let t3_threshold = tier_threshold(context_window, TIER3_FRACTION);

    let needs_t3 = messages.len() >= COMPACT_MESSAGE_THRESHOLD
        || estimated_tokens >= t3_threshold;

    // ── Tier 3: Full compaction ───────────────────────────────────────
    if needs_t3 && last_tier.as_u8() < CheckpointTier::Compacted.as_u8() {
        info!(
            "Tier 3 compaction: {} messages (~{} tokens, threshold {})",
            messages.len(), estimated_tokens, t3_threshold
        );

        // Read checkpoint.md if available to enrich the summary
        let checkpoint_context = if let Some(cp_path) = checkpoint_path {
            read_file_content(cp_path).await
        } else {
            None
        };

        // Also read any remaining notes
        let notes_context = if let Some(n_path) = notes_path {
            let content = read_file_content(n_path).await;
            // Clear notes after reading
            if content.is_some() {
                clear_file(n_path).await;
            }
            content
        } else {
            None
        };

        let split_point = messages.len().saturating_sub(KEEP_RECENT);
        let old_messages = &messages[..split_point];
        let recent_messages = &messages[split_point..];

        let old_text = messages_to_text(old_messages);

        let mut summary_prompt = String::new();
        if let Some(cp) = &checkpoint_context {
            if !cp.trim().is_empty() {
                summary_prompt.push_str("Previous checkpoint state:\n");
                summary_prompt.push_str(cp);
                summary_prompt.push_str("\n\n");
            }
        }
        if let Some(notes) = &notes_context {
            if !notes.trim().is_empty() {
                summary_prompt.push_str("Session notes:\n");
                summary_prompt.push_str(notes);
                summary_prompt.push_str("\n\n");
            }
        }
        summary_prompt.push_str(
            "Summarize the following conversation concisely. Your summary MUST include:\n\n\
             1. **Active intent**: The user's most ORIGINAL request that started this work, \
             VERBATIM BLOCK-QUOTED. This is the single most important thing to preserve. \
             If the user gave one request at the start, that is the intent — do not let it \
             be overwritten by intermediate exploration or tangential work.\n\
             2. **Next concrete action**: The single next step to take when resuming. \
             Be specific: name files to edit, commands to run, or changes to make.\n\
             3. **What was completed**: Key accomplishments and code changes made so far.\n\
             4. **Current state**: What is in progress. List SPECIFIC file paths being edited.\n\
             5. **Key decisions**: Technical choices and their rationale.\n\
             6. **Errors and fixes**: Issues encountered and how resolved.\n\n\
             CRITICAL RULES:\n\
             - §1 must contain a verbatim block-quoted user request (> \"exact words\"). \
             Use the user's FIRST substantive request, not a later clarification.\n\
             - §2 must be an actionable directive the agent can execute immediately.\n\
             - §4 must list the exact file paths the agent was reading or writing.\n\
             - The agent wakes up with ONLY this summary — it must know exactly where to continue.\n\
             - Do NOT include git status, git diff, or unrelated repository state in the summary. \
             Only include context directly relevant to the user's active request.\n\n"
        );
        summary_prompt.push_str(&old_text);

        let request = MessageRequest {
            model: provider.model().to_string(),
            system: Some(system_prompt.to_string()),
            messages: vec![Message::user(&summary_prompt)],
            tools: vec![],
            max_tokens: 2048,
            temperature: None,
            thinking_budget: None,
        };

        let mut stream = provider.create_message_stream(request).await?;
        let mut summary = String::new();

        while let Some(event) = stream.next().await {
            match event? {
                StreamEvent::TextDelta(text) => summary.push_str(&text),
                StreamEvent::Done { .. } => break,
                StreamEvent::Error(msg) => return Err(RustyError::Api(msg)),
                _ => {}
            }
        }

        debug!("Compacted {} messages into summary", split_point);

        let summary_with_plan = if let Some(plan) = plan_text {
            format!("{summary}\n\n{plan}")
        } else {
            summary
        };
        let mut new_messages = Vec::new();
        new_messages.push(Message::user(format!(
            "[Previous conversation summary]\n{summary_with_plan}"
        )));
        new_messages.push(Message::assistant(
            "Understood. I have the context from our previous conversation.",
        ));
        new_messages.extend_from_slice(recent_messages);

        *messages = new_messages;

        let new_tokens = estimate_tokens(messages);
        info!(
            "After compaction: {} messages (~{} tokens)",
            messages.len(),
            new_tokens
        );

        return Ok(CheckpointTier::Compacted);
    }

    // ── Tier 2: Structured extraction ─────────────────────────────────
    if estimated_tokens >= t2_threshold && last_tier.as_u8() < CheckpointTier::Extracted.as_u8() {
        info!(
            "Tier 2 extraction: ~{} tokens (threshold {})",
            estimated_tokens, t2_threshold
        );

        // Read and clear notes
        let notes_content = if let Some(n_path) = notes_path {
            let content = read_file_content(n_path).await;
            if content.is_some() {
                clear_file(n_path).await;
            }
            content
        } else {
            None
        };

        if let Some(cp_path) = checkpoint_path {
            extract_checkpoint(
                messages,
                provider,
                system_prompt,
                cp_path,
                notes_content.as_deref(),
            )
            .await?;
        }

        // Also run micro-compaction at this tier
        micro_compact(messages);

        return Ok(CheckpointTier::Extracted);
    }

    // ── Tier 1: Micro-compaction ──────────────────────────────────────
    if estimated_tokens >= t1_threshold && last_tier.as_u8() < CheckpointTier::Micro.as_u8() {
        info!(
            "Tier 1 micro-compaction: ~{} tokens (threshold {})",
            estimated_tokens, t1_threshold
        );
        if micro_compact(messages) {
            return Ok(CheckpointTier::Micro);
        }
    }

    Ok(last_tier)
}

// ── Force compaction (used by /compact command) ─────────────────────────────

/// Force compaction regardless of thresholds — used for /compact command.
/// If `plan_text` is provided, it is appended to the summary.
pub async fn force_compact(
    messages: &mut Vec<Message>,
    provider: &dyn LlmProvider,
    system_prompt: &str,
    plan_text: Option<&str>,
    notes_path: Option<&Path>,
    checkpoint_path: Option<&Path>,
) -> Result<bool, RustyError> {
    if messages.len() < 4 {
        return Ok(false);
    }

    info!("Force compacting: {} messages", messages.len());

    // Read checkpoint and notes for context
    let checkpoint_context = if let Some(cp_path) = checkpoint_path {
        read_file_content(cp_path).await
    } else {
        None
    };
    let notes_context = if let Some(n_path) = notes_path {
        let content = read_file_content(n_path).await;
        if content.is_some() {
            clear_file(n_path).await;
        }
        content
    } else {
        None
    };

    let split_point = messages.len().saturating_sub(KEEP_RECENT);
    let old_messages = &messages[..split_point];
    let recent_messages = &messages[split_point..];

    let old_text = messages_to_text(old_messages);

    let mut summary_prompt = String::new();
    if let Some(cp) = &checkpoint_context {
        if !cp.trim().is_empty() {
            summary_prompt.push_str("Previous checkpoint state:\n");
            summary_prompt.push_str(cp);
            summary_prompt.push_str("\n\n");
        }
    }
    if let Some(notes) = &notes_context {
        if !notes.trim().is_empty() {
            summary_prompt.push_str("Session notes:\n");
            summary_prompt.push_str(notes);
            summary_prompt.push_str("\n\n");
        }
    }
    summary_prompt.push_str(
        "Summarize the following conversation concisely. Your summary MUST include:\n\n\
         1. **Active intent**: The user's most ORIGINAL request, VERBATIM BLOCK-QUOTED.\n\
         2. **Next concrete action**: The single next step, with specific file paths.\n\
         3. **What was completed**: Key accomplishments and code changes.\n\
         4. **Current state**: What is in progress, specific files being edited.\n\
         5. **Key decisions**: Technical choices and their rationale.\n\n\
         CRITICAL: §1 must contain a verbatim block-quoted user request. \
         The agent wakes up with ONLY this summary.\n\n"
    );
    summary_prompt.push_str(&old_text);

    let request = MessageRequest {
        model: provider.model().to_string(),
        system: Some(system_prompt.to_string()),
        messages: vec![Message::user(&summary_prompt)],
        tools: vec![],
        max_tokens: 2048,
        temperature: None,
        thinking_budget: None,
    };

    let mut stream = provider.create_message_stream(request).await?;
    let mut summary = String::new();

    while let Some(event) = stream.next().await {
        match event? {
            StreamEvent::TextDelta(text) => summary.push_str(&text),
            StreamEvent::Done { .. } => break,
            StreamEvent::Error(msg) => return Err(RustyError::Api(msg)),
            _ => {}
        }
    }

    debug!("Force compacted {} messages into summary", split_point);

    let summary_with_plan = if let Some(plan) = plan_text {
        format!("{summary}\n\n{plan}")
    } else {
        summary
    };
    let mut new_messages = Vec::new();
    new_messages.push(Message::user(format!(
        "[Previous conversation summary]\n{summary_with_plan}"
    )));
    new_messages.push(Message::assistant(
        "Understood. I have the context from our previous conversation.",
    ));
    new_messages.extend_from_slice(recent_messages);

    *messages = new_messages;
    Ok(true)
}

// ── Helpers ─────────────────────────────────────────────────────────────────

/// Read file content, returning None if the file doesn't exist or is empty.
pub async fn read_file_content(path: &Path) -> Option<String> {
    match tokio::fs::read_to_string(path).await {
        Ok(content) if !content.trim().is_empty() => Some(content),
        _ => None,
    }
}

/// Truncate a file to zero length (clear it).
pub async fn clear_file(path: &Path) {
    let _ = tokio::fs::write(path, "").await;
}

/// Estimate token count for messages.
/// Counts ALL content blocks (text, tool results, tool use, thinking) rather
/// than just text, so compaction triggers when context is actually full.
pub fn estimate_tokens(messages: &[Message]) -> usize {
    let mut total_chars: usize = 0;
    for msg in messages {
        total_chars += 16; // per-message overhead (~4 tokens)
        match &msg.content {
            rusty_core::MessageContent::Text(text) => {
                total_chars += text.len();
            }
            rusty_core::MessageContent::Blocks(blocks) => {
                for block in blocks {
                    match block {
                        rusty_core::ContentBlock::Text { text } => {
                            total_chars += text.len();
                        }
                        rusty_core::ContentBlock::Thinking { thinking } => {
                            total_chars += thinking.len();
                        }
                        rusty_core::ContentBlock::ToolUse { id, name, input } => {
                            total_chars += id.len() + name.len();
                            total_chars += input.to_string().len();
                            total_chars += 32;
                        }
                        rusty_core::ContentBlock::ToolResult { content, tool_use_id, .. } => {
                            total_chars += content.len() + tool_use_id.len() + 32;
                        }
                        rusty_core::ContentBlock::Image { .. } => {
                            total_chars += 256;
                        }
                    }
                }
            }
        }
    }
    ((total_chars as f64 * 1.2 / 4.0).ceil() as usize).max(1)
}

pub fn messages_to_text(messages: &[Message]) -> String {
    let mut parts = Vec::new();
    for msg in messages {
        let role = match msg.role {
            Role::User => "User",
            Role::Assistant => "Assistant",
        };
        let text = msg.get_all_text();
        if !text.is_empty() {
            parts.push(format!("{role}: {text}"));
        }
    }
    parts.join("\n\n")
}

/// Extract a section from a checkpoint markdown file by its `## §N Title` header.
/// Returns the section body (everything until the next `## §` header or end of file).
#[allow(dead_code)] // used by tests; available for future rebuild-context consumers
pub(crate) fn extract_section<'a>(checkpoint: &'a str, section_header: &str) -> Option<&'a str> {
    let start = checkpoint.find(section_header)?;
    let body_start = start + checkpoint[start..].find('\n')?;
    let rest = &checkpoint[body_start..];
    let end = rest[1..]
        .find("\n## §")
        .map(|i| i + 1)
        .unwrap_or(rest.len());
    Some(&rest[..end])
}

/// Extract the last N user messages as plain text, for verbatim preservation
/// in the rebuild context. Skips compaction boundary messages and empty texts.
pub fn recent_user_messages(messages: &[Message], count: usize) -> Vec<String> {
    messages
        .iter()
        .rev()
        .filter(|m| m.role == Role::User)
        .filter_map(|m| {
            let text = m.get_all_text();
            if text.contains("[Previous conversation summary]")
                || text.contains("Conversation history was automatically compacted")
            {
                return None;
            }
            if text.trim().is_empty() {
                return None;
            }
            Some(text)
        })
        .take(count)
        .collect::<Vec<_>>()
        .into_iter()
        .rev()
        .collect()
}

/// Generate a tail-aware reminder based on the last message role in the
/// preserved tail. Mirrors MiMo Code's tail-aware system reminders.
pub fn tail_aware_reminder(messages: &[Message]) -> &'static str {
    let last = match messages.last() {
        Some(m) => m,
        None => return "",
    };
    match last.role {
        Role::Assistant => {
            if last.has_tool_use() {
                "The previous assistant turn made tool calls. Process the tool results \
                 and continue your work loop."
            } else {
                "The previous assistant turn ended. Check your task list before stopping \
                 again — if work remains, continue."
            }
        }
        Role::User => "",
    }
}

/// Render the full rebuild context that is injected as a synthetic user message
/// after Tier 3 compaction. Modeled after MiMo Code's renderRebuildContext().
///
/// Assembles: checkpoint.md content, notes.md content, recent verbatim user
/// messages, seam framing, and a tail-aware reminder into a single message
/// that tells the agent exactly where to resume.
pub async fn render_rebuild_context(
    checkpoint_path: Option<&Path>,
    notes_path: Option<&Path>,
    messages: &[Message],
) -> String {
    let mut lines: Vec<String> = Vec::new();

    // Header: explicit framing that this is a continuation
    lines.push(
        "This session is being continued from a previous conversation that was \
         compacted to save context space. The checkpoint and notes below cover \
         the earlier portion of the conversation."
            .to_string(),
    );
    lines.push(String::new());

    // Section 1: Session checkpoint (full body)
    if let Some(cp_path) = checkpoint_path {
        if let Some(checkpoint) = read_file_content(cp_path).await {
            if !checkpoint.trim().is_empty() {
                lines.push("## Session checkpoint".to_string());
                lines.push(checkpoint.trim().to_string());
                lines.push(String::new());
            }
        }
    }

    // Section 2: Session notes (full body)
    if let Some(n_path) = notes_path {
        if let Some(notes) = read_file_content(n_path).await {
            if !notes.trim().is_empty() {
                lines.push("## Session notes".to_string());
                lines.push(notes.trim().to_string());
                lines.push(String::new());
            }
        }
    }

    // Section 3: Recent user messages (verbatim)
    let recent = recent_user_messages(messages, 5);
    if !recent.is_empty() {
        lines.push("## Recent user input (verbatim)".to_string());
        for msg in &recent {
            if msg.len() > 2000 {
                lines.push(format!("> {}...(truncated)", &msg[..2000]));
            } else {
                lines.push(format!("> {msg}"));
            }
        }
        lines.push(String::new());
    }

    // Section 4: Seam framing — explicit resume instructions
    lines.push(
        "Recent messages are preserved below — the assistant turn (and any tool results) \
         you will see is real history, not pseudo-content. Continue your task by responding \
         to the most recent state."
            .to_string(),
    );
    lines.push(String::new());
    lines.push(
        "Resume directly. Do not acknowledge this memory dump, do not recap, \
         do not preface with \"I will continue\" or similar. Pick up the last task \
         as if the break never happened."
            .to_string(),
    );

    // Section 5: Tail-aware reminder
    let reminder = tail_aware_reminder(messages);
    if !reminder.is_empty() {
        lines.push(String::new());
        lines.push(reminder.to_string());
    }

    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── estimate_tokens ──────────────────────────────────────────────

    #[test]
    fn estimate_empty_messages() {
        let msgs: Vec<Message> = vec![];
        assert_eq!(estimate_tokens(&msgs), 1); // max(1) floor
    }

    #[test]
    fn estimate_single_message() {
        let msgs = vec![Message::user("hello")]; // 5 chars + 16 overhead = 21
        let tokens = estimate_tokens(&msgs);
        assert_eq!(tokens, 7); // ceil(21 * 1.2 / 4) = 7
    }

    #[test]
    fn estimate_scales_with_content() {
        let short = vec![Message::user("hi")];
        let long = vec![Message::user("a".repeat(1000))];
        assert!(estimate_tokens(&long) > estimate_tokens(&short));
    }

    #[test]
    fn estimate_400_chars_is_125_tokens() {
        let msgs = vec![Message::user("a".repeat(400))]; // 400 + 16 = 416
        assert_eq!(estimate_tokens(&msgs), 125); // ceil(416 * 1.2 / 4) = 125
    }

    // ── messages_to_text ─────────────────────────────────────────────

    #[test]
    fn messages_to_text_basic() {
        let msgs = vec![Message::user("hello"), Message::assistant("hi there")];
        let text = messages_to_text(&msgs);
        assert_eq!(text, "User: hello\n\nAssistant: hi there");
    }

    #[test]
    fn messages_to_text_skips_empty() {
        let msgs = vec![
            Message::user("hello"),
            Message::user(""),    // empty — skipped
            Message::assistant("ok"),
        ];
        let text = messages_to_text(&msgs);
        assert_eq!(text, "User: hello\n\nAssistant: ok");
    }

    #[test]
    fn messages_to_text_empty_list() {
        let msgs: Vec<Message> = vec![];
        assert_eq!(messages_to_text(&msgs), "");
    }

    // ── micro_compact ────────────────────────────────────────────────

    #[test]
    fn micro_compact_replaces_long_tool_results() {
        use rusty_core::ContentBlock;

        // Need > KEEP_RECENT messages so the first one is in the old group
        let mut msgs: Vec<Message> = (0..11)
            .map(|i| {
                if i == 0 {
                    Message::user_blocks(vec![ContentBlock::ToolResult {
                        tool_use_id: "1".into(),
                        content: "a".repeat(1000),
                        is_error: Some(false),
                    }])
                } else {
                    Message::assistant("ok")
                }
            })
            .collect();

        let modified = micro_compact(&mut msgs);
        assert!(modified);
        let block_text = match &msgs[0].content {
            rusty_core::MessageContent::Blocks(blocks) => match &blocks[0] {
                ContentBlock::ToolResult { content, .. } => content.clone(),
                _ => panic!("expected ToolResult"),
            },
            _ => panic!("expected Blocks"),
        };
        assert!(block_text.contains("Old tool result content cleared"));
    }

    #[test]
    fn micro_compact_skips_short_tool_results() {
        use rusty_core::ContentBlock;

        let mut msgs = vec![
            Message::user_blocks(vec![ContentBlock::ToolResult {
                tool_use_id: "1".into(),
                content: "short".into(),
                is_error: Some(false),
            }]),
            Message::assistant("ok"),
        ];

        let modified = micro_compact(&mut msgs);
        assert!(!modified);
    }

    #[test]
    fn micro_compact_preserves_recent_messages() {
        use rusty_core::ContentBlock;

        // All messages are in the recent window
        let mut msgs: Vec<Message> = (0..5)
            .map(|_| {
                Message::user_blocks(vec![ContentBlock::ToolResult {
                    tool_use_id: "1".into(),
                    content: "a".repeat(1000),
                    is_error: Some(false),
                }])
            })
            .collect();

        let modified = micro_compact(&mut msgs);
        assert!(!modified); // all in KEEP_RECENT window
    }

    // ── CheckpointTier ───────────────────────────────────────────────

    #[test]
    fn checkpoint_tier_roundtrip() {
        for v in 0..=3 {
            assert_eq!(CheckpointTier::from_u8(v).as_u8(), v);
        }
        assert_eq!(CheckpointTier::from_u8(99).as_u8(), 3); // saturates
    }

    // ── extract_section ────────────────────────────────────────────

    #[test]
    fn extract_section_finds_intent() {
        let cp = "\
# Session checkpoint

## §1 Active intent
> Transfer the site files to index.html

## §2 Next concrete action
Read rusty-website (1).html and extract content.

## §3 Directives (this session)
(none)
";
        let intent = extract_section(cp, "§1 Active intent").unwrap();
        assert!(intent.contains("Transfer the site files"));
        let next = extract_section(cp, "§2 Next concrete action").unwrap();
        assert!(next.contains("Read rusty-website"));
    }

    #[test]
    fn extract_section_returns_none_for_missing() {
        let cp = "## §1 Active intent\nhello\n";
        assert!(extract_section(cp, "§99 Missing").is_none());
    }

    #[test]
    fn extract_section_last_section_goes_to_eof() {
        let cp = "## §11 Open notes\nSome notes here.\nNo trailing section.";
        let body = extract_section(cp, "§11 Open notes").unwrap();
        assert!(body.contains("Some notes here."));
        assert!(body.contains("No trailing section."));
    }

    // ── recent_user_messages ───────────────────────────────────────

    #[test]
    fn recent_user_messages_skips_compaction_boundaries() {
        let msgs = vec![
            Message::user("First real request"),
            Message::assistant("Working on it"),
            Message::user("[Previous conversation summary]\nSome summary"),
            Message::user("Second real request"),
            Message::assistant("Done"),
        ];
        let recent = recent_user_messages(&msgs, 10);
        assert_eq!(recent.len(), 2);
        assert!(recent[0].contains("First real request"));
        assert!(recent[1].contains("Second real request"));
    }

    #[test]
    fn recent_user_messages_limits_count() {
        let msgs: Vec<Message> = (0..10)
            .map(|i| Message::user(format!("Request {i}")))
            .collect();
        let recent = recent_user_messages(&msgs, 3);
        assert_eq!(recent.len(), 3);
        assert!(recent[0].contains("Request 7"));
        assert!(recent[2].contains("Request 9"));
    }

    #[test]
    fn recent_user_messages_empty_on_no_user() {
        let msgs = vec![Message::assistant("hello")];
        let recent = recent_user_messages(&msgs, 5);
        assert!(recent.is_empty());
    }

    // ── tail_aware_reminder ────────────────────────────────────────

    #[test]
    fn tail_aware_reminder_for_assistant_with_tools() {
        use rusty_core::ContentBlock;
        let msgs = vec![Message::assistant_blocks(vec![
            ContentBlock::Text {
                text: "Let me check".into(),
            },
            ContentBlock::ToolUse {
                id: "1".into(),
                name: "bash".into(),
                input: serde_json::json!({"command": "ls"}),
            },
        ])];
        let reminder = tail_aware_reminder(&msgs);
        assert!(reminder.contains("tool calls"));
        assert!(reminder.contains("continue your work loop"));
    }

    #[test]
    fn tail_aware_reminder_for_assistant_without_tools() {
        let msgs = vec![Message::assistant("Done with the task.")];
        let reminder = tail_aware_reminder(&msgs);
        assert!(reminder.contains("task list"));
    }

    #[test]
    fn tail_aware_reminder_for_user_message() {
        let msgs = vec![Message::user("Do this")];
        let reminder = tail_aware_reminder(&msgs);
        assert_eq!(reminder, "");
    }

    #[test]
    fn tail_aware_reminder_empty_messages() {
        let msgs: Vec<Message> = vec![];
        let reminder = tail_aware_reminder(&msgs);
        assert_eq!(reminder, "");
    }

    // ── render_rebuild_context ─────────────────────────────────────

    #[tokio::test]
    async fn render_rebuild_context_with_checkpoint_and_notes() {
        let dir = tempfile::tempdir().unwrap();
        let cp_path = dir.path().join("checkpoint.md");
        let notes_path = dir.path().join("notes.md");

        tokio::fs::write(
            &cp_path,
            "# Session checkpoint\n\n## §1 Active intent\n> Transfer site files\n\n## §2 Next concrete action\nRead the HTML files.\n",
        )
        .await
        .unwrap();
        tokio::fs::write(&notes_path, "# Notes\n\n## [turn 1]\nFound template in rusty-website.\n")
            .await
            .unwrap();

        let msgs = vec![
            Message::user("Take a look at the site folder"),
            Message::assistant("I'll read the files."),
        ];

        let result = render_rebuild_context(Some(&cp_path), Some(&notes_path), &msgs).await;

        // Should contain the continuation framing
        assert!(result.contains("continued from a previous conversation"));
        // Should contain checkpoint content
        assert!(result.contains("## Session checkpoint"));
        assert!(result.contains("Transfer site files"));
        assert!(result.contains("Read the HTML files"));
        // Should contain notes
        assert!(result.contains("## Session notes"));
        assert!(result.contains("Found template"));
        // Should contain recent user messages
        assert!(result.contains("## Recent user input"));
        assert!(result.contains("Take a look at the site folder"));
        // Should contain seam framing
        assert!(result.contains("Resume directly"));
        assert!(result.contains("Do not acknowledge this memory dump"));
    }

    #[tokio::test]
    async fn render_rebuild_context_no_files() {
        let msgs = vec![Message::user("Hello"), Message::assistant("Hi there")];

        let result = render_rebuild_context(None, None, &msgs).await;

        // Should still have framing and recent messages
        assert!(result.contains("continued from a previous conversation"));
        assert!(result.contains("## Recent user input"));
        assert!(result.contains("Hello"));
        assert!(result.contains("Resume directly"));
        // Should NOT have checkpoint or notes sections
        assert!(!result.contains("## Session checkpoint"));
        assert!(!result.contains("## Session notes"));
    }

    #[tokio::test]
    async fn render_rebuild_context_empty_checkpoint() {
        let dir = tempfile::tempdir().unwrap();
        let cp_path = dir.path().join("checkpoint.md");
        tokio::fs::write(&cp_path, "").await.unwrap();

        let msgs = vec![Message::user("Test")];
        let result = render_rebuild_context(Some(&cp_path), None, &msgs).await;

        // Empty checkpoint should be skipped
        assert!(!result.contains("## Session checkpoint"));
        assert!(result.contains("Resume directly"));
    }

    #[tokio::test]
    async fn render_rebuild_context_no_user_messages() {
        let msgs = vec![Message::assistant("Working on it...")];

        let result = render_rebuild_context(None, None, &msgs).await;

        // No user messages → no "Recent user input" section
        assert!(!result.contains("## Recent user input"));
        // But should still have framing
        assert!(result.contains("Resume directly"));
    }

    #[tokio::test]
    async fn render_rebuild_context_includes_tail_reminder() {
        let dir = tempfile::tempdir().unwrap();
        let cp_path = dir.path().join("checkpoint.md");
        tokio::fs::write(
            &cp_path,
            "## §1 Active intent\n> Do the thing\n",
        )
        .await
        .unwrap();

        // Last message is assistant with tool use → should get "continue your work loop"
        use rusty_core::ContentBlock;
        let msgs = vec![Message::assistant_blocks(vec![
            ContentBlock::Text {
                text: "Let me check".into(),
            },
            ContentBlock::ToolUse {
                id: "1".into(),
                name: "bash".into(),
                input: serde_json::json!({"command": "ls"}),
            },
        ])];

        let result = render_rebuild_context(Some(&cp_path), None, &msgs).await;
        assert!(result.contains("tool calls"));
        assert!(result.contains("continue your work loop"));
    }

    #[tokio::test]
    async fn render_rebuild_context_truncates_long_messages() {
        let msgs = vec![Message::user("a".repeat(3000))];

        let result = render_rebuild_context(None, None, &msgs).await;
        // Should be truncated at 2000 chars + "(truncated)"
        assert!(result.contains("(truncated)"));
        assert!(result.len() < 3500); // not the full 3000 chars
    }
}
